<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Format email yang dimasukkan belum sesuai</name>
   <tag></tag>
   <elementGuidId>3b9b9dd1-f588-4fdb-9fc3-52e1c191d0c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b1-Input']/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.validation-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7e8d16ae-bcf5-4964-9e12-c95613024050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>validation-message</value>
      <webElementGuid>dd78ad28-d42f-44fe-8629-5fe6cb0622d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Format email yang dimasukkan belum sesuai. Contoh : biko.maryono@gmail.com</value>
      <webElementGuid>6adb0be1-e8c7-4166-aa71-8e194552eed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b1-Input&quot;)/span[@class=&quot;input-email&quot;]/span[@class=&quot;validation-message&quot;]</value>
      <webElementGuid>bd47f89d-0b8c-4424-9c72-4dc6e0037d3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b1-Input']/span/span</value>
      <webElementGuid>f01cecd4-924d-4951-9ac7-cf3a31a3602e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::span[2]</value>
      <webElementGuid>d18e9913-f096-4b61-832f-3190636795d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim'])[1]/preceding::span[1]</value>
      <webElementGuid>643318c8-5725-4bbc-b4a3-f7ba1ceda569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali ke halaman'])[1]/preceding::span[1]</value>
      <webElementGuid>a216ba2e-aa17-443d-90d0-cef70bd5370b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Format email yang dimasukkan belum sesuai. Contoh : biko.maryono@gmail.com']/parent::*</value>
      <webElementGuid>c846080a-5174-4393-b85f-1dd093c24a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>b8afd29d-0d26-495f-91fc-850b7841e596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Format email yang dimasukkan belum sesuai. Contoh : biko.maryono@gmail.com' or . = 'Format email yang dimasukkan belum sesuai. Contoh : biko.maryono@gmail.com')]</value>
      <webElementGuid>5e83f058-2255-45b4-8e95-c25df2c22a95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
