<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Cari Mobil Impian</name>
   <tag></tag>
   <elementGuidId>0ff78cd0-7120-43e7-bef6-addbbd207055</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b5-BtnNormalSearch']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-BtnNormalSearch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e79a2ec8-c330-4720-8433-59b6ae7c626a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>1fedfced-026f-4d36-9b8c-3fc4c990d3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a9c6ad3b-220f-4edf-8756-306f25ca0a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-BtnNormalSearch</value>
      <webElementGuid>b60af615-3dba-4978-aab0-15907c1630f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari Mobil Impian</value>
      <webElementGuid>f302fdf5-0ca8-4e8c-89f4-4b255738aa37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-BtnNormalSearch&quot;)</value>
      <webElementGuid>bb8aa680-d468-46dc-95e1-eb4469069d8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b5-BtnNormalSearch']</value>
      <webElementGuid>7537aef3-57f3-4bed-ae11-e47370d02256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-search_container']/div/div/div/div/div[2]/button</value>
      <webElementGuid>791f86a3-f7a1-4eeb-833d-a334798aedbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil Baru'])[2]/following::button[1]</value>
      <webElementGuid>b47d76ec-3b5f-4d97-9da4-77fcbc785f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Semua Promo'])[1]/following::button[1]</value>
      <webElementGuid>8e76346c-bb9a-4f8b-8f71-dac6af1ad05d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Search'])[1]/preceding::button[1]</value>
      <webElementGuid>8f7221cc-84c3-48a4-a9de-0db6f36d18e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Mobil Impian'])[2]/preceding::button[1]</value>
      <webElementGuid>2524c6fb-6703-450b-a1a2-e9e575507c47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari Mobil Impian']/parent::*</value>
      <webElementGuid>a7bb67b7-be7e-43fc-b102-975d9e9ac833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>f037604b-efdd-442a-928a-8ff198ce8eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b5-BtnNormalSearch' and (text() = 'Cari Mobil Impian' or . = 'Cari Mobil Impian')]</value>
      <webElementGuid>40d9f116-b498-4198-b83b-4da1e9c464db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
