<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Daihatsu</name>
   <tag></tag>
   <elementGuidId>36ab6cb4-d14b-44d4-9a75-b28f59ad0a78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b5-b14-Content']/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>abfadfa7-08ae-419e-aa0f-98856f647397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white-container car-brand</value>
      <webElementGuid>d0fb3a0e-e889-4dd8-a948-76cc0a98d360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f6d995b8-429d-46db-8ae7-0a65b870a53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b14-Content&quot;)/div[@class=&quot;list list-group OSFillParent&quot;]/div[@class=&quot;car-brand__container&quot;]/a[@class=&quot;white-container car-brand&quot;]</value>
      <webElementGuid>a51c73cb-6e5f-41ee-a994-166964a86eb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b14-Content']/div/div[2]/a</value>
      <webElementGuid>a4afb8fa-5bf5-43fe-b26a-6429f342feee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOYOTA'])[1]/following::a[1]</value>
      <webElementGuid>a540f010-d709-44a1-b5ec-a7aa26293e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilihan Brand Terbaik untuk Kamu'])[1]/following::a[2]</value>
      <webElementGuid>7ff66847-8a04-4e01-a10a-b06ebc6a6b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAIHATSU'])[1]/preceding::a[1]</value>
      <webElementGuid>2577be16-7dd0-4000-ab38-6075e347356b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil baru dari SEVA'])[1]/preceding::a[1]</value>
      <webElementGuid>356f89a9-0ed0-4b61-ab53-554f4d91d722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[6]</value>
      <webElementGuid>a3dca835-0ac7-4373-9363-0c2c3e3f1e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/a</value>
      <webElementGuid>16280206-395a-4549-9c8f-a0ac61e4d239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>a4ecd301-f8a0-4243-aeab-1864660a448c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
