<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MobilBaru-Search</name>
   <tag></tag>
   <elementGuidId>567d85be-9d6e-49ba-a04f-cf54e0948c3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-Input_NormalVar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#b5-Input_NormalVar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddf32bd6-d2a3-44e2-a2e9-99202b953932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>1068a4bb-7eec-4e75-a5ee-93b0b26c37b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>d970051a-b07f-49d7-9645-a1b75e40c451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Toyota Avanza</value>
      <webElementGuid>333e7d78-6f5c-4e4b-9c1f-add2c0c0db93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Input_NormalVar</value>
      <webElementGuid>95787a19-108a-4cae-948d-e15c7a5d8deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Input_NormalVar&quot;)</value>
      <webElementGuid>706772e6-c023-47e5-a7e2-2d0dd36869f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-Input_NormalVar']</value>
      <webElementGuid>e5317eea-5f1c-4f5a-8d15-54b3ca761369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-search_container']/div/div/div/div/div/span/input</value>
      <webElementGuid>94455266-541d-41ec-a569-ddf28e5ced0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span/input</value>
      <webElementGuid>753affa6-74d8-454c-8736-022401dd98f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Contoh: Toyota Avanza' and @id = 'b5-Input_NormalVar']</value>
      <webElementGuid>ffe11471-2fd7-45b9-9777-eb9bc456e02a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
