<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Toyota</name>
   <tag></tag>
   <elementGuidId>a8b6f72b-e200-4e1c-91c8-ce63310f7ad1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.white-container.car-brand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>92946a27-c2a4-49ba-a9e9-c0b8a9456630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>white-container car-brand</value>
      <webElementGuid>5fed9b29-8d21-480b-873e-10ecb3a35094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>deab0583-92aa-47f9-8647-c298cd68d684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-b14-Content&quot;)/div[@class=&quot;list list-group OSFillParent&quot;]/div[@class=&quot;car-brand__container&quot;]/a[@class=&quot;white-container car-brand&quot;]</value>
      <webElementGuid>0afb6793-eeb6-4a76-a875-2f267ca064a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b14-Content']/div/div/a</value>
      <webElementGuid>5889ba16-55a2-4a1e-8d61-3adab7d030ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilihan Brand Terbaik untuk Kamu'])[1]/following::a[1]</value>
      <webElementGuid>84c07004-5511-4745-a0e8-c9a1b9b10a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Search'])[2]/following::a[1]</value>
      <webElementGuid>803a9cc1-3508-4798-a761-1917de38b3fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOYOTA'])[1]/preceding::a[1]</value>
      <webElementGuid>1902e06b-e6a0-40ab-97d2-2b5ca99241d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAIHATSU'])[1]/preceding::a[2]</value>
      <webElementGuid>da4df7a3-9ca1-4f9c-ad47-303a677fd52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>7e3e6cbc-4be8-4293-808e-2c70c5be2cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/a</value>
      <webElementGuid>88873c17-dea8-4f26-8d1c-990a02e25bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#']</value>
      <webElementGuid>a884e5e9-44f0-4ca3-89f8-2b7a191f3d9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
