<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Karir</name>
   <tag></tag>
   <elementGuidId>caad2532-1421-46bb-9a2e-cc696b79dd4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-LayoutWrapper']/div[4]/div/div/div[2]/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eeef6368-4b42-4447-b3c4-bb2f5c4f9f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://career.acc.co.id/ACCRedBerries/Homepage</value>
      <webElementGuid>38163dcc-4af1-4f47-891b-83c0380d7083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Karir</value>
      <webElementGuid>4638db20-007f-4293-ad4f-61d927fc62cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-LayoutWrapper&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;header-top-wrapper OSInline&quot;]/div[@class=&quot;flex-justify-between container full-height&quot;]/div[@class=&quot;header-top__menu m-d-none&quot;]/div[@class=&quot;header-top__menu-link&quot;]/a[1]</value>
      <webElementGuid>986e5aa3-b6bb-44e4-9175-6dc6a9a7e31c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-LayoutWrapper']/div[4]/div/div/div[2]/div[4]/a</value>
      <webElementGuid>52616785-b115-47aa-93f9-784fc350e868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Karir')]</value>
      <webElementGuid>7b771e7e-6541-48d6-b892-5bc24d49d58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/following::a[1]</value>
      <webElementGuid>ec0a8f22-9447-45dd-a340-8b0692772a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang ACC'])[1]/following::a[2]</value>
      <webElementGuid>97754fd8-293f-4864-8f5a-d19df349f672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::a[2]</value>
      <webElementGuid>cdef135d-d839-4e44-8e68-e1af0069c9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informasi lainnya'])[1]/preceding::a[3]</value>
      <webElementGuid>7ee1c6e8-82a5-457c-af0f-a083490e92bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Karir']/parent::*</value>
      <webElementGuid>6751335a-0de5-4a75-a9f6-83ee74e27790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://career.acc.co.id/ACCRedBerries/Homepage')]</value>
      <webElementGuid>43ceb6ef-581e-4d92-8e08-084339d69f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>d5e9eb6d-45b1-4aa4-aeee-6536ce99e0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://career.acc.co.id/ACCRedBerries/Homepage' and (text() = 'Karir' or . = 'Karir')]</value>
      <webElementGuid>bed491b0-6499-49f1-a472-28e041414cab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
