<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <elementGuidId>2d92a194-3e54-4d16-9eb9-f31395b77f1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.header-login.not-login.padding-base.m-d-none</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-$b3']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7a7552b2-cd9c-4d4e-b4bb-6329cf412df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header-login not-login padding-base m-d-none</value>
      <webElementGuid>44fef637-8433-4766-b3a0-e0607dd58640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/accone/Loginpage</value>
      <webElementGuid>708e50a2-0002-47aa-830a-451aa103e943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>c0475f19-7c53-426f-b92f-ea129560b566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-$b3&quot;)/div[@class=&quot;user-info&quot;]/a[@class=&quot;header-login not-login padding-base m-d-none&quot;]</value>
      <webElementGuid>dbb9d762-97fd-4120-8b7d-bb61836ac019</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-$b3']/div/a</value>
      <webElementGuid>4932ec04-4540-496c-8e0b-a05fb6fdbe5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalkulator Kredit'])[1]/following::a[1]</value>
      <webElementGuid>4ff86a6e-6fdb-4ccf-a6fe-86b315fd02a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Debit'])[1]/following::a[2]</value>
      <webElementGuid>01d7e251-9f40-43e0-9bfa-01121dd2e67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email atau Nomor Handphone'])[1]/preceding::a[1]</value>
      <webElementGuid>8c291c5b-4427-4a1e-be00-32bdb5557a5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/accone/Loginpage')]</value>
      <webElementGuid>9d2ada23-7970-4f60-8f07-d1bdab8e3460</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/a</value>
      <webElementGuid>2cc09109-4e12-4efc-a166-0fb1006ae252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/accone/Loginpage' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>20e27897-0566-4963-b17a-50e0411763ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
