<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MobileLink</name>
   <tag></tag>
   <elementGuidId>4d3adcfa-e4ce-401e-a906-6901f848a26c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ThemeGrid_MarginGutter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-LayoutWrapper']/div[4]/div/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b67739ee-5dce-4541-814c-72e1f3195e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ThemeGrid_MarginGutter</value>
      <webElementGuid>0e88ef22-8a62-4995-a7c7-08a3899b7ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download aplikasi ACC ONE</value>
      <webElementGuid>6ad11278-bd95-4b73-ab6a-22d874923c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-LayoutWrapper&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;header-top-wrapper OSInline&quot;]/div[@class=&quot;flex-justify-between container full-height&quot;]/div[@class=&quot;download-header position-relative&quot;]/span[@class=&quot;ThemeGrid_MarginGutter&quot;]</value>
      <webElementGuid>4b51f05c-c84c-488b-a932-5976330f00a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-LayoutWrapper']/div[4]/div/div/div/span</value>
      <webElementGuid>c42987ee-35ae-4878-a711-633a0c7af7fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusat Bantuan'])[1]/preceding::span[1]</value>
      <webElementGuid>d720a127-e824-4f32-96c6-c6606f57e0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang ACC'])[1]/preceding::span[1]</value>
      <webElementGuid>4aa9a597-b3d5-4524-b1fd-9c6f5570b967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download aplikasi ACC ONE']/parent::*</value>
      <webElementGuid>73a46064-388f-4e2f-b1be-9a26f79a464c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>8dcc982a-c1aa-4186-a8fe-d13cac3f561a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Download aplikasi ACC ONE' or . = 'Download aplikasi ACC ONE')]</value>
      <webElementGuid>d67ee79d-cb6e-4ed1-b909-827d754aa83c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
