<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert_Username atau Password salah</name>
   <tag></tag>
   <elementGuidId>394ebb84-1f55-4ddb-a6d0-d4ede8edc8fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='feedbackMessageContainer']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.feedback-message.feedback-message-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>219d9280-abac-4dbf-8290-727ed4037e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feedback-message feedback-message-error</value>
      <webElementGuid>b327967c-a04f-4a38-8f99-874c947b5731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Username atau Password salah</value>
      <webElementGuid>16243ee3-ae11-4fe7-95c5-f49c2149f4bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;feedbackMessageContainer&quot;)/div[@class=&quot;feedback-message feedback-message-error&quot;]</value>
      <webElementGuid>f8f19623-d3c4-48ad-a7d2-8a3a6636ffdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='feedbackMessageContainer']/div</value>
      <webElementGuid>62d21c8f-9b7e-49c7-8a14-d5ba49a3fbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download aplikasi ACC ONE'])[1]/preceding::div[5]</value>
      <webElementGuid>695dc2cb-2fbc-4d9a-9f94-155272658bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
      <webElementGuid>66151256-012f-4a63-8b0e-0cfdc66bf882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Username atau Password salah' or . = 'Username atau Password salah')]</value>
      <webElementGuid>4bc4786a-aa29-4ac3-8d49-8aa2cb7e1905</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
