<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profileName</name>
   <tag></tag>
   <elementGuidId>85821579-512a-49b6-b2be-4dbebd3a717f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-$b3']/div/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.font-semi-bold</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>981a5a94-8d18-4a17-9495-740b867eddd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-semi-bold</value>
      <webElementGuid>49c9dd61-5fa2-46c2-8029-a2a930edcec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Goldie</value>
      <webElementGuid>a1046c1a-519f-499a-9638-bd34fb1beb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-$b3&quot;)/div[@class=&quot;user-info&quot;]/div[@class=&quot;user-info-login&quot;]/div[@class=&quot;font-size-base&quot;]/span[@class=&quot;font-semi-bold&quot;]</value>
      <webElementGuid>0e7eea81-12af-40d4-bdbc-b1ed8a2bd5d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-$b3']/div/div/div/span[2]</value>
      <webElementGuid>6973c83e-28f6-4110-b7a2-7c4f0e8c6200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi,'])[1]/following::span[1]</value>
      <webElementGuid>f708b413-93b5-4b43-8ce0-b8e03686d0c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalkulator Kredit'])[1]/following::span[2]</value>
      <webElementGuid>dddc9f7d-7a60-429e-9ab2-fb5284f015bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saldo AstraPay'])[1]/preceding::span[1]</value>
      <webElementGuid>29cbde54-68d7-4888-af90-b050d91ac962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::span[2]</value>
      <webElementGuid>9e486c98-1508-4b9a-8b58-7425a2333dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Goldie']/parent::*</value>
      <webElementGuid>8ca5f07d-535e-47c6-bfac-11e8ad47d0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>cdf2c365-beb1-4edc-a57b-f6d0c801ed97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Goldie' or . = 'Goldie')]</value>
      <webElementGuid>c8fdce17-ce02-4d46-a8be-df14eb2e352b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
