<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>profile</name>
   <tag></tag>
   <elementGuidId>6e70d430-85f1-4cb3-a0b8-bc77269d628d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-$b3']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.user-info-login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>683da469-65b0-497a-838f-5829ef1cac2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-info-login</value>
      <webElementGuid>c56fb672-571b-4fe7-a479-96536b76fb9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hi, Goldie</value>
      <webElementGuid>f1afd77e-338f-4c35-81fe-d4f468a9b613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-$b3&quot;)/div[@class=&quot;user-info&quot;]/div[@class=&quot;user-info-login&quot;]</value>
      <webElementGuid>9ebb62a6-fdfb-4987-babd-80c084a8e94c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-$b3']/div/div</value>
      <webElementGuid>714c508e-ff00-490d-9c05-b8f2e31a92a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kalkulator Kredit'])[1]/following::div[7]</value>
      <webElementGuid>442eabb1-57f8-406d-b8f7-cd026a84d183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Auto Debit'])[1]/following::div[8]</value>
      <webElementGuid>9bb89e32-99a4-474b-a904-5252bbf1d976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div[4]/div/div/div</value>
      <webElementGuid>3c5ac358-cbf5-407f-b42f-4b08b513df2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Hi, Goldie' or . = 'Hi, Goldie')]</value>
      <webElementGuid>8458f9d2-4d98-47b5-a606-0caa18af1180</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
