<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mobil List</name>
   <tag></tag>
   <elementGuidId>7e47eedf-d7a4-4631-a1e9-4023955caaed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/a/div[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3ec42f77-8e03-4e3d-9300-c2424f2da922</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TOYOTA ALL NEW VOXY</value>
      <webElementGuid>a81463a6-12b5-417e-b6f0-036ee01f7028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-l17-290_1-Link_V2&quot;)/div[2]/div[@class=&quot;car__name&quot;]/span[1]</value>
      <webElementGuid>8de08f8e-037f-4521-90bc-8e0f36279d37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='b5-l17-290_1-Link_V2']/div[2]/div/span</value>
      <webElementGuid>25cea3df-de19-4f7d-aee9-9d8fb7bd4534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOYOTA NEW AGYA'])[1]/following::span[1]</value>
      <webElementGuid>e4f9293e-86e6-4592-9be1-bf897b51fdb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Angsuran Termahal - Termurah'])[1]/following::span[2]</value>
      <webElementGuid>c87b0645-542c-4582-8675-dc9b6391bc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOYOTA ALL NEW RUSH'])[1]/preceding::span[1]</value>
      <webElementGuid>78ba0338-25a8-4dff-9c96-256a29d199fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOYOTA ALL NEW ALPHARD'])[1]/preceding::span[2]</value>
      <webElementGuid>f9fb743e-4d96-4bc1-be34-4f35d7f329ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TOYOTA ALL NEW VOXY']/parent::*</value>
      <webElementGuid>66e48acb-eb5f-4272-b2c0-5275bcc1c888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a/div[2]/div/span</value>
      <webElementGuid>fcb9f3be-0989-4856-8ab4-a7b63077f637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TOYOTA ALL NEW VOXY' or . = 'TOYOTA ALL NEW VOXY')]</value>
      <webElementGuid>db969f88-2b6d-4cbe-8c2a-83804f455799</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
