<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iOS</name>
   <tag></tag>
   <elementGuidId>280c2297-ade0-4e61-8fe2-dabbdcfaaba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a > div</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b1-LayoutWrapper']/div[4]/div/div/div/div/div[1]/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>34623775-d63a-4a7c-9210-cf8cbae4b6a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iOS</value>
      <webElementGuid>16eeb77e-5f98-43ca-9d8a-15ae5df4bd67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b1-LayoutWrapper&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;header-top-wrapper OSInline&quot;]/div[@class=&quot;flex-justify-between container full-height&quot;]/div[@class=&quot;download-header position-relative&quot;]/div[@class=&quot;select_download&quot;]/div[@class=&quot;ThemeGrid_Width6&quot;]/a[1]/div[1]</value>
      <webElementGuid>f13c0512-5791-4ea8-ba47-3e40160d6f61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b1-LayoutWrapper']/div[4]/div/div/div/div/div/a/div</value>
      <webElementGuid>9cb03c2e-9f54-499a-8a39-c040138efda6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download aplikasi ACC ONE'])[1]/following::div[3]</value>
      <webElementGuid>d51a2fab-ebc0-4f39-af8a-a17e1f13ed77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Android'])[1]/preceding::div[2]</value>
      <webElementGuid>d5aa69f6-4b8c-41ca-a5c5-d1f3abba6c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>4a069dbf-7441-4068-9af9-b026cf74a950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'iOS' or . = 'iOS')]</value>
      <webElementGuid>b95bf008-b94f-43fb-aeea-3cb289385d8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
