<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Beli Mobil Baru</name>
   <tag></tag>
   <elementGuidId>ce2d93d8-de86-4bc9-83f0-4734f8d93414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-MenuCariMobil']/div[2]/a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sub-menu__item.flex-justify-between</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f954274-4470-45d7-b092-0e93000bf0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-menu__item flex-justify-between</value>
      <webElementGuid>9bdb4f54-6fd2-4004-940f-c8855a6a8157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/accone/NewCar_catalog?title=Daftar-Harga-Mobil-Baru</value>
      <webElementGuid>055f764f-20a6-40c1-adf7-e7d3b19d9ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beli Mobil Baru</value>
      <webElementGuid>c6b53647-bba8-428e-947a-9eb50dddacab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-MenuCariMobil&quot;)/div[@class=&quot;sub-menu cari-mobil OSInline&quot;]/a[@class=&quot;sub-menu__item flex-justify-between&quot;]</value>
      <webElementGuid>9e52cccb-d031-4752-9309-479c6ab02344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-MenuCariMobil']/div[2]/a</value>
      <webElementGuid>3f9753c4-ea72-433f-9e48-caa3620224eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Beli Mobil Baru')]</value>
      <webElementGuid>1158a809-8478-44ed-990f-8bc6c82f1440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jual/Beli Mobil'])[1]/following::a[1]</value>
      <webElementGuid>f0d02e36-a2d0-4d97-a230-06cebeff1326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seputar Produk'])[1]/following::a[2]</value>
      <webElementGuid>6a070706-3375-4777-b019-9627208ab46f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli Mobil Bekas'])[1]/preceding::a[1]</value>
      <webElementGuid>e0747600-6c9c-426e-be71-354beba27e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jual Mobil'])[1]/preceding::a[2]</value>
      <webElementGuid>102af38b-9795-4aad-b55f-8c50f8edc29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beli Mobil Baru']/parent::*</value>
      <webElementGuid>5827ec96-a0ea-473f-af44-f78b265ce5d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/accone/NewCar_catalog?title=Daftar-Harga-Mobil-Baru')]</value>
      <webElementGuid>c5422620-bb0b-43a6-8bdc-4263667c30d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/a</value>
      <webElementGuid>55866144-b867-480e-88f8-579e6e28ac3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/accone/NewCar_catalog?title=Daftar-Harga-Mobil-Baru' and (text() = 'Beli Mobil Baru' or . = 'Beli Mobil Baru')]</value>
      <webElementGuid>036fdb13-117d-4126-b355-c5c5b29783ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
