<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Jual Mobil</name>
   <tag></tag>
   <elementGuidId>622bb2bd-cc0d-4e95-9b2f-24be605bed2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-MenuCariMobil']/div[2]/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c177b112-7cf9-4c62-a435-a40e1dd60144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-menu__item flex-justify-between ThemeGrid_MarginGutter</value>
      <webElementGuid>e0e2fa6d-0ece-413c-8dac-798a55f503dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.acc.co.id/accdrivethru/</value>
      <webElementGuid>e4967734-14cf-4ef8-84a0-aa3145f55758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jual Mobil</value>
      <webElementGuid>aa5d6e4f-94fe-4c40-a003-6f75bc515c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-MenuCariMobil&quot;)/div[@class=&quot;sub-menu cari-mobil OSInline&quot;]/a[@class=&quot;sub-menu__item flex-justify-between ThemeGrid_MarginGutter&quot;]</value>
      <webElementGuid>5ed59af9-df0c-4656-bdf7-45d4bbd2cfbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-MenuCariMobil']/div[2]/a[3]</value>
      <webElementGuid>6dc2cf24-d3e8-4604-89f3-416c39137be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Jual Mobil')]</value>
      <webElementGuid>8542ac7b-0eea-4c64-ad9a-2bd009de91d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli Mobil Bekas'])[1]/following::a[1]</value>
      <webElementGuid>f7339c49-cf03-47c4-ba42-d88c3b5e0987</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Beli Mobil Baru'])[1]/following::a[2]</value>
      <webElementGuid>e1a8fb0e-9769-4730-b42b-f36a7c5fcbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari Dana'])[1]/preceding::a[1]</value>
      <webElementGuid>2e726241-e88e-49a4-bf6f-1c268ca4ed06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fasilitas Dana'])[1]/preceding::a[2]</value>
      <webElementGuid>f9a58739-c3c1-4b61-884c-3c27be12f972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jual Mobil']/parent::*</value>
      <webElementGuid>50479fb5-bdbb-4ca0-8104-5ba094db9459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.acc.co.id/accdrivethru/')]</value>
      <webElementGuid>2f7e62aa-7d1a-433d-b0db-c16d6e3cbf2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>62f8d0bf-71ef-4d1c-862d-44faa3164c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.acc.co.id/accdrivethru/' and (text() = 'Jual Mobil' or . = 'Jual Mobil')]</value>
      <webElementGuid>56d56ef9-4087-415f-8cdb-9f9bf9a7fbf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
