<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HasilPencarian</name>
   <tag></tag>
   <elementGuidId>03b7a95e-504c-448b-8956-c65a657b944c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-l2-187_9-b7-b1-hdesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div/div/div/div/div/div/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>57ef0ca5-8afa-4be9-9448-1f96cab1952f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>a322f23e-60aa-4ae3-81cb-bb8f319b89b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-l2-187_9-b7-b1-hdesc</value>
      <webElementGuid>b3858d0c-1d98-4c4b-b845-552ac524de42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACC Syariah memberikan fasilitas kredit mobil baru dari berbagai merek dan jenis kendaraan sesuai prinsip syariah.</value>
      <webElementGuid>12e036da-c1de-4287-b494-a490ae62b360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-l2-187_9-b7-b1-hdesc&quot;)</value>
      <webElementGuid>8f8063ba-3934-4607-98a8-0d34c21d37ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='b5-l2-187_9-b7-b1-hdesc']</value>
      <webElementGuid>67298fd1-9d65-420e-9206-4c715bb6c87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-l2-187_9-b7-$b1']/div</value>
      <webElementGuid>d30d1e11-ddc2-42b6-9917-614c62110f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk ACC Syariah Mobil Baru'])[1]/following::div[2]</value>
      <webElementGuid>54c91485-b356-459a-ade4-ee45683028fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACC Syariah Mobil Baru'])[2]/following::div[4]</value>
      <webElementGuid>5ad69c23-0d64-4eb2-9409-b023803a13fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat detail'])[1]/preceding::div[1]</value>
      <webElementGuid>3384c94f-363f-4343-9179-7945097afcaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACC Syariah memberikan fasilitas kredit']/parent::*</value>
      <webElementGuid>385b975d-6169-4f52-8090-056fe9478f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/div/div/div[2]/div[2]/div</value>
      <webElementGuid>35567a84-301c-4457-93b1-5b9b32f3e100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'b5-l2-187_9-b7-b1-hdesc' and (text() = 'ACC Syariah memberikan fasilitas kredit mobil baru dari berbagai merek dan jenis kendaraan sesuai prinsip syariah.' or . = 'ACC Syariah memberikan fasilitas kredit mobil baru dari berbagai merek dan jenis kendaraan sesuai prinsip syariah.')]</value>
      <webElementGuid>524fc8cb-e8f9-45c2-9c2b-7b002dbbc2e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
