<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Syariah</name>
   <tag></tag>
   <elementGuidId>54cf9547-ca73-48b2-b73e-3a1b2e2de782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b4-MenuSyariah']/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>835ff7ae-870c-4ea3-b92d-b83f8bd91c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-header-item </value>
      <webElementGuid>a8f0b77a-cbf0-4005-a323-9cbdfc6b8eeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/accone/Produk?index=2</value>
      <webElementGuid>1121250f-7934-410f-b230-7f84708f7eda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Syariah</value>
      <webElementGuid>4f550601-affe-4a08-a100-4c2faf0b43e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b4-MenuSyariah&quot;)/div[@class=&quot;flex-justify-between text-menu&quot;]/a[@class=&quot;menu-header-item&quot;]</value>
      <webElementGuid>dbd31e68-e433-44f3-86af-87a70f71c770</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b4-MenuSyariah']/div/a</value>
      <webElementGuid>39d6527c-cd65-41a0-a205-6e57e63f78d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Syariah')]</value>
      <webElementGuid>f89fcce4-b39f-40d3-b001-5c7624cf4dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prioritas Dana'])[1]/following::a[1]</value>
      <webElementGuid>f32896de-5972-43b4-9f5e-4013e01bbfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fasilitas Dana'])[1]/following::a[2]</value>
      <webElementGuid>58493160-7341-485d-a1c9-d15c9241aa0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACC Syariah Mobil Baru'])[1]/preceding::a[1]</value>
      <webElementGuid>0f0a731e-0a88-4888-8d6a-1ac6b7a63118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACC Syariah Mobil Bekas'])[1]/preceding::a[2]</value>
      <webElementGuid>29a45a33-174b-444a-9bc8-4c1c0e43cea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Syariah']/parent::*</value>
      <webElementGuid>53b62f25-c983-45d0-9bd8-38be10dc72cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/accone/Produk?index=2')]</value>
      <webElementGuid>90056665-bc9b-4d42-875b-1bf76811b9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>8fee255e-2eb3-4a55-ba92-341a5372a956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/accone/Produk?index=2' and (text() = 'Syariah' or . = 'Syariah')]</value>
      <webElementGuid>46957565-487f-42ff-87f9-8a6171444c78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
