<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputNoHP</name>
   <tag></tag>
   <elementGuidId>03157be2-25c8-47e0-b039-6eff245d586b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-Input_Phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-Input_Phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a480cb2-6771-4341-82ef-cf5812e69fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>99fe79e6-1d9a-4518-8c04-a4b0c2137393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>07b2894d-b03c-4e8a-abc9-cc41382554f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3bd227de-a6e7-4c26-abb0-9822645aeb68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Input_Phone</value>
      <webElementGuid>088d8a83-11bc-486e-be24-344566cde5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Input_Phone&quot;)</value>
      <webElementGuid>02da8c04-a462-46b5-abc7-71f271e51f0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-Input_Phone']</value>
      <webElementGuid>519bc3df-d586-4142-9f99-21605c683fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b4-Input']/span/input</value>
      <webElementGuid>1b9a2cfa-0202-4679-9f0e-b43ba9ab038e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span/input</value>
      <webElementGuid>196ce772-551f-4931-a70e-b46296284ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'b5-Input_Phone']</value>
      <webElementGuid>8e4a0f29-b02b-4f20-8c71-fd75319ad336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
