<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputConfPass</name>
   <tag></tag>
   <elementGuidId>ba765146-e528-43ed-b1de-c876ce2610e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-Input_KonfirmSandi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-Input_KonfirmSandi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c8df202-762c-46fe-970f-84c9e58811ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>2e36af75-7505-4347-83f4-0456080f2400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2fba89fa-7d65-4c5e-bfe3-108950a8fd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>629c11bf-e25a-420f-bf7a-bb02f86eedae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Input_KonfirmSandi</value>
      <webElementGuid>eb9c294b-70d2-48d2-948d-377e9f94d07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Input_KonfirmSandi&quot;)</value>
      <webElementGuid>457a9000-af26-423a-bf17-2f6f7ee6e17d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-Input_KonfirmSandi']</value>
      <webElementGuid>7576c739-86a4-4572-ad31-a97e2dbf5ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-InputKonfirmKataSandi']/span/input</value>
      <webElementGuid>3a384f44-09e7-4271-b26e-e3602ed059e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div/div/div[2]/div/span/input</value>
      <webElementGuid>ff64be4d-6581-4736-bc29-45e6b70c734b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'b5-Input_KonfirmSandi']</value>
      <webElementGuid>84036f1d-4570-4bef-b9f5-2e99615b2745</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
