<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputEmail</name>
   <tag></tag>
   <elementGuidId>c0c73703-be1d-4dc0-b223-cc3e9be98c5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-Input_Email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-Input_Email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81c90c8f-82f1-4e88-99fe-1ae2d3a9812c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>1e4b84a2-5b14-44b7-907c-c233c5c1551a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>f848992a-1b38-4ca5-b8df-8f55ebb125bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5d0679b0-2b49-4c96-8445-1d28df8ff7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Input_Email</value>
      <webElementGuid>272bf672-5bfe-44a8-8b06-163e5a85f746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Input_Email&quot;)</value>
      <webElementGuid>13f77267-7bf6-49c1-a371-9aa8e9da90d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-Input_Email']</value>
      <webElementGuid>ce56161c-08c2-49f4-9830-5131027ee355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b3-Input']/span/input</value>
      <webElementGuid>7ac46fe3-5ead-42fa-a8c6-e55972b0a0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/span/input</value>
      <webElementGuid>f33893e0-2059-4629-a729-ae371f0bddc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'b5-Input_Email']</value>
      <webElementGuid>f64f9ea5-80dc-4c85-8ca4-d02408f1ff0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
