<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputNama</name>
   <tag></tag>
   <elementGuidId>1c88c190-fe89-49b3-bdf8-9c61ee345c57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-Input_NamaLengkap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-Input_NamaLengkap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9552e41e-c4bf-44a5-9778-de878d7b1cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>32a3f6ee-e811-45bf-a521-444287156f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce10f6ab-9cba-4d96-b89b-f08f72897f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>4c40a312-b50a-4242-8c0b-d61895fa2c72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Input_NamaLengkap</value>
      <webElementGuid>a3021cdc-373f-4184-9fa4-72c7465b9167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Input_NamaLengkap&quot;)</value>
      <webElementGuid>2e06a898-7133-46b5-8f95-ef231e96f097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-Input_NamaLengkap']</value>
      <webElementGuid>e6684395-4c2e-4c75-ba60-895b91b98d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-b2-Input']/span/input</value>
      <webElementGuid>59539921-3e8d-4bd7-a515-7afc80ab7121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/span/input</value>
      <webElementGuid>40c46066-670d-4a5e-b153-77d7f818ebd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'b5-Input_NamaLengkap']</value>
      <webElementGuid>5eab361f-be9f-48fd-94ef-9cd2375dea9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
