<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputRadiobtnLaki</name>
   <tag></tag>
   <elementGuidId>9d3c5e7e-55e2-4b29-891b-ace942ad2a6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-RadioButton1-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-RadioButton1-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>846675ac-ef7c-4cf3-941b-3d0bf00cd760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>df1209e2-0a6c-4cf9-8f6e-271268d65335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-RadioButton1-input</value>
      <webElementGuid>b5947519-e17f-43f3-a624-fb4f0e7f2437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>da045583-3b4e-4a8b-8bf1-7dde87f5a0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b5-RadioGroup1</value>
      <webElementGuid>6890056c-2a7d-4ec9-a3a0-55c2c131046d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>17b4dbf3-f287-452d-815a-251d55f73dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-RadioButton1-input&quot;)</value>
      <webElementGuid>6cad81e8-f755-424c-8b89-49861c6d59e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-RadioButton1-input']</value>
      <webElementGuid>a7a2b69b-73d8-432d-a27f-1e9be839918f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-RadioButton1']/input</value>
      <webElementGuid>726399b9-c9c6-4641-bdc1-6fbafe1adceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>977b3024-d9d3-40b3-ade7-30db9b462a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b5-RadioButton1-input' and @name = 'b5-RadioGroup1']</value>
      <webElementGuid>1c2af607-f4c9-4442-a322-88dd64c8e35b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
