<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputRadiobtnPerempuan</name>
   <tag></tag>
   <elementGuidId>c8aeaede-4bf2-49aa-9c9b-ea4094318c3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-RadioButton2-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-RadioButton2-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e6ceeb6f-645d-458d-ba89-9685f91d7682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>58e98444-ed88-4a50-b75d-61ffee94507b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-RadioButton2-input</value>
      <webElementGuid>553af663-9322-4bea-879b-e0b07639b6f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-button</value>
      <webElementGuid>77262331-2d65-454b-858d-342d8c2b795f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b5-RadioGroup1</value>
      <webElementGuid>9c0fa30c-3506-46e0-a5cc-70af7eb45b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>F</value>
      <webElementGuid>5ceb671b-5adb-4dc8-845d-b9e9ba6e3040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-RadioButton2-input&quot;)</value>
      <webElementGuid>95e87d77-ee45-4d68-853b-55a281ce35ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-RadioButton2-input']</value>
      <webElementGuid>0a6431a7-c54c-420a-90a4-040c5ab1cc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-RadioButton2']/input</value>
      <webElementGuid>b99bee53-c1f1-4969-95b3-620ca546c3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>a27c1dd6-5d8b-46d8-8184-faf181ca8c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'b5-RadioButton2-input' and @name = 'b5-RadioGroup1']</value>
      <webElementGuid>2676b930-f37e-4871-b31e-99c5b25cca7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
