<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Cari Mobil Impian</name>
   <tag></tag>
   <elementGuidId>fa80dd44-a781-4561-861c-8835ccf42efa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-CariNormal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='b5-CariNormal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5fac7354-da8e-4f53-b5fc-f328b36f01c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>cb5a3d6b-0b2c-4b62-9e5e-c5796768c41c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>407aefd7-83fe-43d6-8515-2a02c20b38fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-CariNormal</value>
      <webElementGuid>80405f0f-df8f-44e7-8a45-6e6e98aa4362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cari Mobil Impian</value>
      <webElementGuid>67f214ac-9f5c-4eb6-8c52-59df557d54df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-CariNormal&quot;)</value>
      <webElementGuid>1be140bb-a949-4514-b8b6-fea0eb13d4ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='b5-CariNormal']</value>
      <webElementGuid>25765456-48ab-4bb6-8503-cc5b787796cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-NormalSearchButton']/button</value>
      <webElementGuid>3a11d621-0115-4900-a4f5-b4231487822e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACC memfasilitasi kredit mobil bekas hampir seluruh merek mobil bekas dengan harga yang kompetitif'])[1]/following::button[1]</value>
      <webElementGuid>f7f599a7-519b-4cd8-a8dd-fd4c6a852631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobil Bekas'])[2]/following::button[1]</value>
      <webElementGuid>870d8e59-6c89-4904-b62a-75982fb5d899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advanced Search'])[1]/preceding::button[1]</value>
      <webElementGuid>7ef07271-c0c4-4fc1-8508-bb6d01459d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DP 0%, Cicilan Mulai 70rb-an/hari'])[1]/preceding::button[1]</value>
      <webElementGuid>6e7730c6-baff-4fae-ab69-43e0fdf8e0f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cari Mobil Impian']/parent::*</value>
      <webElementGuid>adaa6ac3-aad6-46ad-a6bd-3375ecc1d368</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/button</value>
      <webElementGuid>73c48508-c07d-414b-9255-e974dbae7512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'b5-CariNormal' and (text() = 'Cari Mobil Impian' or . = 'Cari Mobil Impian')]</value>
      <webElementGuid>758e6b24-0caa-41e0-96b0-40038c5ed09c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
