<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MobilBekas-Search</name>
   <tag></tag>
   <elementGuidId>6857abfc-2ecb-4945-8ed3-79cd51d2b21d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b5-Input_NormalTextVar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='b5-Input_NormalTextVar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5787759-985c-4f8b-a98d-31f8b6d51a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control OSFillParent</value>
      <webElementGuid>db67861b-e668-4f9c-a2dc-6247eb484576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b2c0323a-4978-428a-9925-8c113d19ab44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: Toyota Avanza</value>
      <webElementGuid>5cd52784-e604-4583-9b29-4bd47fb8fc79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b5-Input_NormalTextVar</value>
      <webElementGuid>5c8aace7-e0d1-444b-94c1-cb639f4155d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b5-Input_NormalTextVar&quot;)</value>
      <webElementGuid>dcfbe860-6334-47ea-a68e-b71d87e99d94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b5-Input_NormalTextVar']</value>
      <webElementGuid>4d1d206e-c203-4c04-b3d7-8d263592c74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b5-NormalSearch']/div/div/div/span/input</value>
      <webElementGuid>45348827-96a3-4a0b-974b-c2c9ce3e829c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/span/input</value>
      <webElementGuid>fc09fd9e-3a7e-4271-a952-0e28d6adf865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Contoh: Toyota Avanza' and @id = 'b5-Input_NormalTextVar']</value>
      <webElementGuid>3db3a6f0-6585-48c6-9445-d369440583bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
